package bomba;

import static bomba.Castle.mat;
import java.awt.Color;

public class menu extends javax.swing.JFrame {
    String tem = null;

    public menu() {
        super("You will always explode like a bitch");
        this.setLocation(500, 150);
        initComponents();
        setSize(380, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jlb_menu = new javax.swing.JLabel();
        jtbtn_mat = new javax.swing.JToggleButton();
        jtbtn_ingles = new javax.swing.JToggleButton();
        jtbtn_historia = new javax.swing.JToggleButton();
        jtbtn_esp = new javax.swing.JToggleButton();
        jtbtn_ciencias = new javax.swing.JToggleButton();
        jtbtn_geograf = new javax.swing.JToggleButton();
        btn_exit = new javax.swing.JButton();
        imag_menu = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setLocation(new java.awt.Point(380, 350));
        setMinimumSize(new java.awt.Dimension(380, 350));
        setPreferredSize(new java.awt.Dimension(380, 350));
        setSize(new java.awt.Dimension(380, 350));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(null);

        jlb_menu.setBackground(new java.awt.Color(0, 0, 0));
        jlb_menu.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jlb_menu.setForeground(new java.awt.Color(255, 0, 0));
        jlb_menu.setText("MENU");
        jPanel1.add(jlb_menu);
        jlb_menu.setBounds(250, 10, 100, 40);

        jtbtn_mat.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_mat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_mat.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_mat.setText("Matemáticas");
        jtbtn_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_matActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_mat);
        jtbtn_mat.setBounds(230, 90, 130, 37);

        jtbtn_ingles.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_ingles.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_ingles.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_ingles.setText("Ingles");
        jtbtn_ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_inglesActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_ingles);
        jtbtn_ingles.setBounds(230, 130, 130, 37);

        jtbtn_historia.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_historia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_historia.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_historia.setText("Historia");
        jtbtn_historia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_historiaActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_historia);
        jtbtn_historia.setBounds(230, 210, 130, 37);

        jtbtn_esp.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_esp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_esp.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_esp.setText("Español");
        jtbtn_esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_espActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_esp);
        jtbtn_esp.setBounds(230, 50, 130, 37);

        jtbtn_ciencias.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_ciencias.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_ciencias.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_ciencias.setText("Ciencias");
        jtbtn_ciencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_cienciasActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_ciencias);
        jtbtn_ciencias.setBounds(230, 170, 130, 37);

        jtbtn_geograf.setBackground(new java.awt.Color(0, 0, 0));
        jtbtn_geograf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtbtn_geograf.setForeground(new java.awt.Color(255, 255, 255));
        jtbtn_geograf.setText("Geografía");
        jtbtn_geograf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn_geografActionPerformed(evt);
            }
        });
        jPanel1.add(jtbtn_geograf);
        jtbtn_geograf.setBounds(230, 250, 130, 37);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomba/exit.png"))); // NOI18N
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(40, 260, 50, 44);

        imag_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomba/imagen_menu.jpg"))); // NOI18N
        jPanel1.add(imag_menu);
        imag_menu.setBounds(0, 0, 440, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbtn_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_matActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("matematicas");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_matActionPerformed

    private void jtbtn_inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_inglesActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("ingles");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_inglesActionPerformed

    private void jtbtn_historiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_historiaActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("historia");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_historiaActionPerformed

    private void jtbtn_espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_espActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("español");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_espActionPerformed

    private void jtbtn_cienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_cienciasActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("ciencias");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_cienciasActionPerformed

    private void jtbtn_geografActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn_geografActionPerformed
        // TODO add your handling code here:
        Castle.main(null);
        Castle.selecc("geografia");
        this.setVisible(false);
    }//GEN-LAST:event_jtbtn_geografActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel imag_menu;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_menu;
    private javax.swing.JToggleButton jtbtn_ciencias;
    private javax.swing.JToggleButton jtbtn_esp;
    private javax.swing.JToggleButton jtbtn_geograf;
    private javax.swing.JToggleButton jtbtn_historia;
    private javax.swing.JToggleButton jtbtn_ingles;
    private javax.swing.JToggleButton jtbtn_mat;
    // End of variables declaration//GEN-END:variables
}
